### PR TITLE
Turn Off 3D Access

### PR DESCRIPTION
**Pull request by SillyInventor**
Do not merge until going public.

### CODE REVIEW

**Comment by chuck211991** [comment]
I'm just sorta curious as to what's going on; you added 3D, now you're keeping all the code around but preventing people from using it?

**Comment by SillyInventor** [comment]
We're leaving the ability to load in projects with 3D for testing (Anishinaabe Arcs is going up). However, while the 2D side seems to have had all it's corners smoothed, I don't feel comfortable that we've thoroughly worked everything out in 3D. So we're limiting access to making new 3D projects until we're more confident in 3D, while still putting up arcs.

I thought about just keeping 3D CSnap one more release cycle, but there was a  CPU usage improvement that I made that I think Eglash is anxious to see deployed everywhere. And truthfully, I want this to be out the door, and to pull the remainder of the CSDT content from the old site by the end of the summer (if possible) so I can concentrate on my work during the semester.

**Comment by ibara** [comment]
> I'm just sorta curious as to what's going on; you added 3D, now you're keeping all the code around but preventing people from using it?

We are purposely not doing things like having multiple branches of CSnap. 3D is that "cool new feature" that James was awesome enough to complete. But that means dropping 40K lines of code into CSnap.

We spent this development cycle making sure 2D suffered no regressions.

**Comment by ibara** [comment]
Merged and tagged!

**Pull request merged**
