### PR TITLE
Merged 3D

### PR DESCRIPTION
**Pull request by SillyInventor**
I have tried a number of the applications, and fixed the problems such that they all appear to run normally. One small caveat is that we need to also update the application_csnap.html at the same time.

Let's take some extra time on this release and put it to the dev site sooner and longer so we can check for bugs I may have missed.

### CODE REVIEW

**Comment by ibara** [comment]
I think we have important fixes that need testing with the community site this week. And I don't want to take away from that.

With that said, it's also important we get this in and tested.

So I'm going to merge this now, but refrain from putting it on the dev site until after we release the new live site on Tuesday.

We'll still have plenty of time to test, and I'll be more on-hand to rapidly update the dev site if necessary (I'll be done moving by then).

**Comment by SillyInventor** [comment]
I know it says removed goals button here... but that was an oversight while hand merging the code. the goals button wasn't there in the prior version, so I removed it.

**Comment by ibara** [comment]
Can you just put that back in? Or is there more to do here?

**Comment by SillyInventor** [comment]
I already have. I will make a few other changes and then make a pull 
request... then you should have the button back... but I maintain, we 
should probably figure out why it was originally removed.

On 8/12/2015 11:51 AM, Brian Callahan wrote:
>
> Can you just put that back in? Or is there more to do here?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/CSnap/Snap--Build-Your-Own-Blocks/pull/55#issuecomment-130351674>.
>

-- 
James Davis

**Comment by ibara** [comment]
I wonder if it's this commit: https://github.com/CSnap/Snap--Build-Your-Own-Blocks/commit/d3d4ff0c674342ed019fcb67325b6c96eb3c0f27

**Pull request merged**
